# python can be used to perform operations on a file.(read and write)
# type of files: text file (.txt , .docx,.log etc.) binary file (.mp4,.mov,.png,etc)
f = open("demo.txt","r")
data = f.read()
print(data)
print(type(data))
f.close()